# Site settings
author: Jacques Plante
title: Coding State of Mind
header-img: img/home-bg.png
email: jonlypaffle@gmail.com
copyright_name: Jacques Plante
description: > # this means to ignore newlines until "baseurl:"
  A blog about a musician turned coder
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  JPlante9117

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
